### ISSUE TITLE
MIZSelect widget shows all options - It does not filter as per queryset  

### ISSUE THREAD

**Issue by sasikumar1978k** [Actionb/mizdb-tomselect#13]
form.py

getapprovedstf = get_approved_staffs_joined_objects('staff_working_details', Office_Code_id = 2)
       
        self.fields['employee'] = forms.ModelChoiceField(
        queryset=STAFFDET.objects.filter(EMPCODE__in = getapprovedstf).order_by('EMPCODE'),
        widget=MIZSelect(STAFFDET,
                         
                            url='mizdb_autocomplete_view'
                           )
           
            )  
![Screenshot from 2023-10-20 10-37-58](https://github.com/Actionb/mizdb-tomselect/assets/23027374/b88faf72-0e24-4ce1-9138-a0677b210ae6)

without using widget
![Screenshot from 2023-10-20 10-39-22](https://github.com/Actionb/mizdb-tomselect/assets/23027374/187e3d56-1217-4dde-bc52-1b7d97d19d7d)

**Comment by Actionb** [comment]
The autocomplete view is what provides the select options for the widget. The queryset of the form field is irrelevant.

Create a new autocomplete view with the desired queryset, and then use the view's name as the widget's url.
```python
# views.py
from mizdb_tomselect.views import AutocompleteView


class MyAutocompleteView(AutocompleteView):
    queryset = my_queryset


# urls.py
urlpatterns = [
    ...,
    path("foo/", MyAutocompleteView.as_view(), name="my_other_autocomplete_view"),
]


# forms.py
widget = MIZSelect(STAFFDET, url='my_other_autocomplete_view'))
```

**Comment by sasikumar1978k** [comment]
thanks
